CREATE TABLE resumes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	raw_text TEXT NOT NULL,
	analysis JSONB,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE vacancies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hh_id BIGINT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    work_schedule JSONB,
    response_letter_required BOOL,
    company_id BIGINT UNIQUE,
    company_name TEXT,
    area TEXT,
    experience TEXT,
    salary TEXT,
    work_formats JSONB,
    work_schedule_by_days JSONB,
    working_hours JSONB,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE matching_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    resume_id BIGINT NOT NULL
        REFERENCES resumes(id),

    vacancy_id BIGINT NOT NULL
        REFERENCES vacancies(id),

    bm25_score DOUBLE PRECISION,
    embedding_score DOUBLE PRECISION,
    llm_score DOUBLE PRECISION,
    total_score DOUBLE PRECISION,

    matched_skills JSONB,
    recap TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (resume_id, vacancy_id)
);